require.config({
  baseUrl:'script/slide/libs',
  paths:{
   slider:'slider'
  }
});
require(['slider'],function(slider){
  //传入容器id，链接及图片地址，切换时间（可选）和滑动速度（可选）
  //================================================================
  console.log(auctionItem)
  slider(
    'ff-slider',
    ['#','#','#'],
    [auctionItem.imgs['path1'],
     auctionItem.imgs['path2'],
     auctionItem.imgs['path3']],
     null,
     80
  );
});